classdef TestPerchloratesPalgo < matlab.unittest.TestCase
    %TestPerchloratesUtil Test Suite for perchlorates_excel_index
    methods (Test)
        function perchlorates_palgo_ijs(testCase)
            n_ext = 2;
            n_c = 3;
            n_a = 1;
            [trial1,trial2] = perchlorates_palgo_ijs(n_ext,n_c,n_a);
            truth1 = [1     1     1     1     1     2     2     2     2     2     3     3     3     3     3     4     4     4     4     4];
            truth2 = [1     2     3     4     5     1     2     3     4     5     1     2     3     4     5     1     2     3     4     5];
            testCase.verifyEqual(trial1,truth1)
            testCase.verifyEqual(trial2,truth2)
        end

        function palgo_cvecmat(testCase)
            trial = mvu(zeros(3),'mmol');
            vec = mvu([1,2,3,4,5,6,7,8,9],'mmol');
            is = [1,1,1,2,2,2,3,3,3];
            js = [1,2,3,1,2,3,1,2,3];
            trial = perchlorates_palgo_cvecmat(trial,vec,is,js);
            truth = mvu([1,2,3;4,5,6;7,8,9],'mmol');
            testCase.verifyEqual(trial,truth)
        end

        function palgo_cmatvec(testCase)
            trial =  mvu([0,0,0,0,0,0,0,0,0],'mmol');
            mat = mvu([1,2,3;4,5,6;7,8,9],'mmol');
            is = [1,1,1,2,2,2,3,3,3];
            js = [1,2,3,1,2,3,1,2,3];
            trial = perchlorates_palgo_cmatvec(mat,trial,is,js);
            truth = mvu([1,2,3,4,5,6,7,8,9],'mmol');
            testCase.verifyEqual(trial,truth)
        end

        function perchlorates_palgo_dorgdt_mat_eq_mat(testCase)
            simulation = struct('input',struct('n_ext',1, ...
                                               'ext_OA',mvu(2,''),...
                                               'rege_OA',mvu(4,''),...
                                               'ext_ak',mvu(0.1,'/ s'),...
                                               'rege_ak',mvu(0.5,'/ s')...
                                               ),...
                                'constants',struct('cations_extracted',{{'Li','Ca','Mg'}},...
                                                   'anions_extracted',{{'ClO4'}})...
                               );
            [real_mat,trial] = perchlorates_palgo_dorgdt_mat(simulation);
            truth_mat = diag(repmat([0.1,0.5,0.5,0.5],1,4));
            truth = mvu(truth_mat,'/ s');
            testCase.verifyEqual(trial,truth)
        end

        function perchlorates_palgo_dorgdt_mat_real_mat(testCase)
            simulation = struct('input',struct('n_ext',1, ...
                                               'ext_OA',mvu(2,''),...
                                               'rege_OA',mvu(4,''),...
                                               'ext_ak',mvu(0.1,'/ s'),...
                                               'rege_ak',mvu(0.5,'/ s')...
                                               ),...
                                'constants',struct('cations_extracted',{{'Li','Ca','Mg'}},...
                                                   'anions_extracted',{{'ClO4'}})...
                               );
            [trial,eq_mat] = perchlorates_palgo_dorgdt_mat(simulation);
            
            Qorg = ConstantsPerchlorates.Qorg.value;
            Vmix = ConstantsPerchlorates.Vmix.value;
            QV = Qorg/Vmix;
            ext_post = 1.5*QV;
            rege_post = 1.25*QV;
            ext_diag = - (0.1+ext_post);
            rege_diag = - (0.5+rege_post);
            truth_mat = [
                        ext_diag,ext_post,0,0;
                        0,rege_diag,rege_post,0;
                        0,0,rege_diag,rege_post;
                        rege_post,0,0,rege_diag];
            truth = mvu(blkdiag(truth_mat,truth_mat,truth_mat,truth_mat),'/ s');
            testCase.verifyTrue(isalmostequal(trial,truth))
        end

        function perchlorates_palgo_daqdt_mat_vec(testCase)
            simulation = struct('input',struct('n_ext',2, ...
                                               'ext_OA',mvu(2,''),...
                                               'rege_OA',mvu(4,''),...
                                               'ext_ak',mvu(0.1,'/ s'),...
                                               'rege_ak',mvu(0.5,'/ s'),...
                                               'ext_feed_c',mvu([1,2,3],'mmol/ L'),...
                                               'ext_feed_a',mvu([4],'mmol/ L'),...
                                               'rege_feed_c',mvu([5,6,7],'mmol/ L'),...
                                               'rege_feed_a',mvu([8],'mmol/ L')...
                                               ),...
                                'constants',struct('cations_extracted',{{'Li','Ca','Mg'}},...
                                                   'anions_extracted',{{'ClO4'}}, ...
                                                   'Qext',mvu(6.67e-7/2,' m^3/ s'), ...
                                                   'Qrege',mvu(6.67e-7/3,' m^3/ s'))...
                               );
            [real_mat,trial,eq_mat] = perchlorates_palgo_daqdt_mat(simulation);
            QV_ext = (6.67e-7/2)/ConstantsPerchlorates.Vmix.value;
            QV_rege = (6.67e-7/3)/ConstantsPerchlorates.Vmix.value;
            ext_factor = 3*QV_ext;
            rege_factor = 5*QV_rege;
            truth_vec = [ext_factor*1;0;rege_factor*5;0;0;
                         ext_factor*2;0;rege_factor*6;0;0;
                         ext_factor*3;0;rege_factor*7;0;0;
                         ext_factor*4;0;rege_factor*8;0;0];
            truth = mvu(truth_vec,'mmol/ L* s');
            testCase.verifyTrue(isalmostequal(trial,truth))
        end 

        function perchlorates_palgo_daqdt_mat_eq_mat(testCase)
            simulation = struct('input',struct('n_ext',1, ...
                                               'ext_OA',mvu(2,''),...
                                               'rege_OA',mvu(4,''),...
                                               'ext_ak',mvu(0.1,'/ s'),...
                                               'rege_ak',mvu(0.5,'/ s'),...
                                               'ext_feed_c',mvu([1,2,3],'mmol/ L'),...
                                               'ext_feed_a',mvu([4],'mmol/ L'),...
                                               'rege_feed_c',mvu([5,6,7],'mmol/ L'),...
                                               'rege_feed_a',mvu([8],'mmol/ L')...
                                               ),...
                                'constants',struct('cations_extracted',{{'Li','Ca','Mg'}},...
                                                   'anions_extracted',{{'ClO4'}}, ...
                                                   'Qext',mvu(6.67e-7/2,' m^3/ s'), ...
                                                   'Qrege',mvu(6.67e-7/3,' m^3/ s'))...
                               );
            [real_mat,vec,trial] = perchlorates_palgo_daqdt_mat(simulation);
            truth_mat = diag(repmat([0.1,0.5,0.5,0.5],1,4));
            truth = mvu(truth_mat,'/ s');
            testCase.verifyEqual(trial,truth)
        end 

        function perchlorates_palgo_daqdt_mat_real_mat(testCase)
            simulation = struct('input',struct('n_ext',2, ...
                                               'ext_OA',mvu(2,''),...
                                               'rege_OA',mvu(4,''),...
                                               'ext_ak',mvu(0.1,'/ s'),...
                                               'rege_ak',mvu(0.5,'/ s'),...
                                               'ext_feed_c',mvu([1,2,3],'mmol/ L'),...
                                               'ext_feed_a',mvu([4],'mmol/ L'),...
                                               'rege_feed_c',mvu([5,6,7],'mmol/ L'),...
                                               'rege_feed_a',mvu([8],'mmol/ L')...
                                               ),...
                                'constants',struct('cations_extracted',{{'Li','Ca','Mg'}},...
                                                   'anions_extracted',{{'ClO4'}}, ...
                                                   'Qext',mvu(6.67e-7/2,' m^3/ s'), ...
                                                   'Qrege',mvu(6.67e-7/3,' m^3/ s'))...
                               );
            [trial,vec,eq_mat] = perchlorates_palgo_daqdt_mat(simulation);
            QV_ext = (6.67e-7/2)/ConstantsPerchlorates.Vmix.value;
            QV_rege = (6.67e-7/3)/ConstantsPerchlorates.Vmix.value;
            prior_ext = 3*QV_ext;
            prior_rege = 5*QV_rege;
            diag_ext = -(0.1 + 3*QV_ext);
            diag_rege = -(0.5 + 5*QV_rege);
            one_mat = [
                       diag_ext,0,0,0,0;
                       prior_ext,diag_ext,0,0,0;
                       0,0,diag_rege,0,0;
                       0,0,prior_rege,diag_rege,0;
                       0,0,0,prior_rege,diag_rege
                      ];
            truth = mvu(blkdiag(one_mat,one_mat,one_mat,one_mat),'/ s');
            testCase.verifyTrue(isalmostequal(trial,truth))
        end 

        function perchlorates_p_pad(testCase)
             trial = perchlorates_p_pad(mvu([1,2,3,4],' mol'),5,2);
             truth = mvu([1,2,NaN,3,4],' mol');
             testCase.verifyEqual(trial,truth)
        end
    end
end